# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3298fda742e5408015df7bf234312118a04be35d81694c0725f6f13c9f9ea2b41c1dd1db2a26517440dd5e91a7c815b75c581ba2d04e4462e7729f997d74185

test:
  secret_key_base: 40482dcb26607266be607fe81480a2c8d678f2d84cfdfb2d0a468564d66ddf896337663f86a44c8c29fea2649c62308f7adb396109093c82e174e5cb53cb1510

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
